// <auto-generated />
using System;
using AspNetProject.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetProject.Infrastructure.Migrations // <-- 1. ИСПРАВЛЕНО
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729151656_InitialCreate")]
    partial class InitialCreate : Migration // <-- 2. ДОБАВЛЕНО ": Migration"
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetProject.Domain.Entities.Booking", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("EventId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("ProcessedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("EventId");

                b.ToTable("bookings", (string)null);
            });

            modelBuilder.Entity("AspNetProject.Domain.Entities.Event", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid");

                b.Property<int>("AvailableSeats")
                    .HasColumnType("integer");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<DateTime>("EndAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("StartAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<int>("TotalSeats")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("events", (string)null);
            });

            modelBuilder.Entity("AspNetProject.Domain.Entities.Booking", b =>
            {
                // 3. ИСПРАВЛЕНО: было "AspNetProject.Models.Event"
                b.HasOne("AspNetProject.Domain.Entities.Event", "Event")
                    .WithMany("Bookings")
                    .HasForeignKey("EventId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Event");
            });

            modelBuilder.Entity("AspNetProject.Domain.Entities.Event", b =>
            {
                b.Navigation("Bookings");
            });
#pragma warning restore 612, 618
        }
    }
}